notifications:
  email: false

rvm:
  - 2.4.2

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
    - DATABASE=hydrox_test

services:
  - postgresql

sudo: false

language: ruby

cache:
  bundler: true

before_script:
  - psql -c 'create database hydrox_test;' -U postges
