# frozen_string_literal: true

# Generated via
#  `rails generate hyrax:work Work`

module Hyrax
  # WorksController generated by hyrax:work
  class WorksController < ApplicationController
    # Adds Hyrax behaviors to the controller.
    include Hyrax::WorksControllerBehavior
    include Hyrax::BreadcrumbsForWorks
    self.curation_concern_type = ::Work

    # Use this line if you want to use a custom presenter
    self.show_presenter = Hyrax::WorkPresenter
  end
end
