suri:
  service_url: <%= ENV['SURI_SERVICE_URL'] %>
  username: <%= ENV['SURI_USERNAME'] %>
  password: <%= ENV['SURI_PASSWORD'] %>
  use_ssl: true
kafka:
  seed_brokers:
    - 'localhost:9092'
  topic: 'test'
  client_id: 'hydrox-app'
