suri:
  service_url: <%= ENV['SURI_SERVICE_URL'] %>
  username: <%= ENV['SURI_USERNAME'] %>
  password: <%= ENV['SURI_PASSWORD'] %>
  use_ssl: true

require_shib_user_authn: true
sso_logout_url: /Shibboleth.sso/Logout?return=https://hydrox-dev.sul.stanford.edu/

s3:
  upload_bucket: <%= ENV['S3_BUCKET_NAME'] %>
