# Generated via
#  `rails generate hyrax:work Work`
module Hyrax
  # WorkForm generated by hyrax:work
  class WorkForm < Hyrax::Forms::WorkForm
    self.model_class = ::Work
    self.terms += [:resource_type]
  end
end
